# Generated by Django 5.1.4 on 2024-12-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0002_product_size_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
